#!/bin/bash

clear

. "/usr/local/bin/shared/shared_write_functions"
. "/usr/local/bin/shared/shared_debug_functions"
available_groups=$(cat /etc/samba/smb.conf | grep "valid users = @" | cut -d ' ' -f 8- | sed 's/@//g' | tr " " "\n" | sort | uniq)
existing_users=$(awk -F ':' '$3>=1000 {print $1}' /etc/passwd)
users_dir="/samba/users/"

# vérifie si un utilisateur existe déjà
# pas de paramètres
function add_user() {
	echo
	read -p "Nom de l'utilisateur à ajouter : " user

	user_exists=$(sort <(echo "$user") <(echo "$existing_users") | uniq -d)

	if [ "$user_exists" ]
	then
	echo "L'utilisateur $user existe déjà !"
	add_user
	fi

	if [ -z "$user" ]
	then
	echo "L'utilisateur ne peut pas être vide !"
        add_user
	fi
}

# vérifie si un groupe n'existe pas
# pas de paramètres
function add_group() {
	echo
	read -p "Groupe du nouvel utilisateur : " group

        group_exists=$(sort <(echo "$group") <(echo "$available_groups") | uniq -d)

        if [ -z "$group_exists" ]
        then
        echo "Le groupe $group n'existe pas !"
        add_group
        fi
}

# vérifie si le mot de passe est valide
# pas de paramètres
function set_password() {
        echo
	smbpasswd -a "$user"

	while [ "$?" != "0" ]
	do
	echo
	echo "Erreur lors de la saisie du mot de passe !"
	set_password
	done
}

debug_show_users

color_title "AJOUT D'UN UTILISATEUR SAMBA" "5"
echo "$line"

bold_title "> NOM UTILISATEUR"
add_user

echo
bold_title "> GROUPE UTILISATEUR"
echo
echo "Groupes disponibles :"
echo "$available_groups"
add_group

# création de l'utilisateur
useradd -Md "$users_dir""$user" -s /usr/sbin/nologin -G "$group" "$user"

echo
bold_title "> MOT DE PASSE UTILISATEUR"
set_password

# activation de l'utilisateur
smbpasswd -e "$user"

# création du dossier uniquement après avoir validé les étapes précédentes
mkdir "$users_dir""$user"
chown "$user":"$user" "$users_dir""$user"
chmod 2770 "$users_dir""$user"

echo
groups=$(sort <(groups "$user" | cut -d ' ' -f 3- | tr " " "\n") <(echo "$available_groups") | uniq -d)
echo "L'utilisateur $user a bien été créé et ajouté au groupe $groups !"

debug_show_users

echo
